language: node_js
node_js:
  - 10
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: JDKSmUnV2euN0NkNe7jYss2CZQB3utu8s9pVK/8PXng1s42nJ9EuVQSzIaerEISWrgS0EGi/lsFOnaItASRU8/w4gAJxKdIX/CNy+gn2xiObJCQdxzCpMPxnkLZkTtGhyTTTaGTFx7MzuMqS9TU69N/M6kzA34A/sUmhfbhvIVM+/S0ylVc63nYnPVYqlOGHujw8dfQb/fgAE617OExXOAsibF9EhEiYpLeywbA9QeXgVJu5X9m8+ETXeAbvw3l2sOoLXcANBcqktu7ElxZM5kxMZf2ApvZmMIWtPjgHHVkFkulSEnf3mExL5WNX81jbRQzFdNA54W76HsuEiKjxO7yMUcdOWgZf9ljnY/e9Bvhl2sXHJL5ueQnFfvJBbeX45m9RKUM+nSFhaH46/2uYMbg+lEczHXGJJDKK7r9UOlNNDBfDLDELSut3gKJC/ORyunjoXLuu1I4nqkLwZ71zuwwo1mxMhRb8Yhq6t8T7WTVVhROvYgSZKIZBkZr+Ph3y9T/3ozOXQQNTUpJqJS1HCyscLrt7NXUn7vwdnti7Pk5Qa/FregyLraGoHAqcz2PA5jwRKRhmQtxpG9hvEeFb5h13Xe6bDytH3YnjH9n7W56zDVpc0qh21oFn19fiHaknIRYhUUq053Qt7iyDcY3m3uhPI834RJUeZZvgNooGRkg=
